// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS43DUwdAybFiNnytMtsYMX9SBRHYN1Xo',
    appId: '1:90510149397:web:281f9ed882d424d8568b1c',
    messagingSenderId: '90510149397',
    projectId: 'oyoapp-72f46',
    authDomain: 'oyoapp-72f46.firebaseapp.com',
    storageBucket: 'oyoapp-72f46.appspot.com',
    measurementId: 'G-Y1D7Q36MS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDmzMD-F1ig0RdXvbdUzmRHHZVxzPCIM',
    appId: '1:90510149397:android:c6ecc885c489b0f2568b1c',
    messagingSenderId: '90510149397',
    projectId: 'oyoapp-72f46',
    storageBucket: 'oyoapp-72f46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUwDolJkYTyjE06eYUHR7hnWIBhfdook',
    appId: '1:90510149397:ios:18f582a70b0a27b2568b1c',
    messagingSenderId: '90510149397',
    projectId: 'oyoapp-72f46',
    storageBucket: 'oyoapp-72f46.appspot.com',
    iosClientId: '90510149397-qk55ml2c13m2ccbaekqde041abs2qntn.apps.googleusercontent.com',
    iosBundleId: 'com.example.oyo',
  );
}
